# Main Configuration File
# This is the default configuration file for the telescope streaming system

# =============================================================================
# CAMERA CONFIGURATION (Unified for all operations)
# =============================================================================
camera:
  # Camera type and basic settings
  camera_type: "opencv"  # "ascom", "alpaca", or "opencv"
  
  # Sensor specifications (important for calibration)
  sensor_width: 6.17     # Sensor width in mm
  sensor_height: 4.55    # Sensor height in mm
  pixel_size: 3.75       # Pixel size in micrometers
  type: "color"          # Camera type (mono, color)
  bit_depth: 8           # Bit depth
  
  # Cooling settings
  cooling:
    enable_cooling: false
    target_temperature: -10.0  # Target temperature in °C
    wait_for_cooling: true     # Wait for temperature stabilization
    cooling_timeout: 300       # Timeout for cooling stabilization in seconds
    stabilization_tolerance: 1.0  # Temperature tolerance in °C
    warmup_rate: 2.0          # Warmup rate in °C per minute
    warmup_final_temp: 15.0   # Final temperature for warmup
    warmup_at_end: true       # Start warmup when stopping observation
    status_interval: 30       # Status update interval in seconds
  
  # ASCOM camera settings
  ascom:
    ascom_driver: "ASCOM.MyCamera.Camera"  # ASCOM driver ID for astro cameras
    exposure_time: 0.1  # Manual exposure time in seconds
    gain: 1.0  # Gain setting
    offset: 50  # Offset setting (0-255 typically)
    readout_mode: 0  # Readout mode (camera-specific)
    binning: 1  # Binning factor (1x1, 2x2, etc.)
    # Optional: Separate filter wheel driver (e.g., for QHY cameras -- "ASCOM.QHYCFW.FilterWheel")
    filter_wheel_driver: null  # Filter wheel driver ID (if applicable)
    
  # Alpaca camera settings
  alpaca:
    host: "localhost"
    port: 11111
    device_id: 0
    exposure_time: 1.0  # Manual exposure time in seconds
    gain: 100.0  # Gain setting
    offset: 50  # Offset setting (0-255 typically)
    readout_mode: 0  # Readout mode (camera-specific)
    binning: [1, 1]  # Binning factor [x, y] for Alpaca
    
  # OpenCV camera settings
  opencv:
    camera_index: 0  # Camera device index
    exposure_time: 0.1  # Exposure time in seconds
    gain: 1.0  # Gain setting
    resolution: [1920, 1080]  # Resolution [width, height]
    frame_rate: 30  # Frame rate

# =============================================================================
# FRAME PROCESSING CONFIGURATION (Image capture and processing)
# =============================================================================
frame_processing:
  enabled: True
  
  # Frame saving settings
  use_timestamps: False  # Enable timestamps in frame filenames
  timestamp_format: "%Y%m%d_%H%M%S"  # Timestamp format for filenames
  use_capture_count: False  # Enable capture count in frame filenames
  
  # Processing settings
  auto_debayer: False  # Auto-debayer color images
  debayer_method: "RGGB"  # Debayer pattern (RGGB, BGGR, GRBG, GBRG)
  
  # Output settings
  output_dir: "captured_frames"  # Directory for captured frames
  cache_dir: "cache"  # Directory for temporary files
  file_format: "PNG"  # File format for saved frames (fits, jpg, png, tiff, etc.)

# =============================================================================
# TELESCOPE CONFIGURATION
# =============================================================================
telescope:
  # Focal length in millimeters
  focal_length: 1000
  # Aperture diameter in millimeters
  aperture: 200
  # Telescope type (refractor, reflector, etc.)
  type: "reflector"
  # Focal ratio (focal_length / aperture)
  focal_ratio: 5.0

# =============================================================================
# MOUNT CONFIGURATION
# =============================================================================
mount:
  # ASCOM driver program ID
  driver_id: "ASCOM.tenmicron_mount.Telescope"
  # Connection timeout in seconds
  connection_timeout: 10
  # Coordinate validation
  validate_coordinates: true
  # Slewing detection settings
  slewing_detection:
    enabled: true  # Enable slewing detection to prevent captures during movement
    check_before_capture: true  # Check slewing status before each capture
    wait_for_completion: false  # Wait for slewing to complete before capturing
    wait_timeout: 300  # Maximum wait time in seconds (5 minutes)
    check_interval: 1.0  # Interval between slewing checks in seconds

# =============================================================================
# PLATE SOLVING CONFIGURATION
# =============================================================================
plate_solve:
  auto_solve: True
  min_solve_interval: 30
  save_plate_solve_frames: True
  plate_solve_dir: "plate_solve_frames"
  default_solver: "platesolve2"
  
  # Settings for PlateSolve2
  platesolve2:
    executable_path: "C:/Program Files (x86)/PlaneWave Instruments/PWI3/PlateSolve2/PlateSolve2.exe"
    working_directory: "C:/Users/BP34_Admin/AppData/Local/Temp"
    timeout: 60
    verbose: True
    auto_mode: True
    number_of_regions: 999
    min_stars: 20
    max_stars: 200
  
  # Settings for Astrometry.net
  astrometry:
    api_key: ""
    api_url: "http://nova.astrometry.net/api/"

# =============================================================================
# OVERLAY CONFIGURATION
# =============================================================================
overlay:
  # Wait indefinitely for plate-solving results before generating overlay
  wait_for_plate_solve: True
  # Field of view in degrees (default if not provided by plate-solving)
  field_of_view: 1.5
  # Maximum magnitude of objects to display
  magnitude_limit: 9.0
  # Include objects without magnitude (e.g. galaxies)
  include_no_magnitude: False
  # Image size for overlay generation
  image_size: [1920, 1080]
  # Font size for text
  font_size: 14
  # Output format for overlays
  output_format: "png"
  # Default filename for overlays
  default_filename: "overlay.png"
  # Maximum length for object names
  max_name_length: 15
  # Use timestamps in overlay filenames
  use_timestamps: False
  # Timestamp format for overlay filenames
  timestamp_format: "%Y%m%d_%H%M%S"
  # Update settings
  update:
    update_interval: 30
    max_retries: 3
    retry_delay: 5
  # Display settings
  display:
    object_color: [255, 0, 0]
    text_color: [255, 255, 255]
    marker_size: 5
    text_offset: [8, -8]

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  verbose: True
  level: "INFO"
  show_emojis: False
  log_to_file: False
  log_file: "telescope_streaming.log"

# =============================================================================
# PLATFORM CONFIGURATION
# =============================================================================
platform:
  fonts:
    windows: ["arial.ttf", "C:/Windows/Fonts/arial.ttf"]
    linux: ["/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", "/usr/share/fonts/TTF/arial.ttf"]
    macos: ["/System/Library/Fonts/Arial.ttf", "/Library/Fonts/Arial.ttf"]

# =============================================================================
# ADVANCED CONFIGURATION
# =============================================================================
advanced:
  debug_coordinates: False
  debug_simbad: False
  save_empty_overlays: True
  auto_recovery: True 