# OST Telescope Streaming Configuration
# =====================================

# Telescope Mount Settings
# ------------------------
mount:
  # ASCOM driver program ID
  driver_id: "ASCOM.tenmicron_mount.Telescope"
  # Connection timeout in seconds
  connection_timeout: 10
  # Coordinate validation
  validate_coordinates: true

# Telescope Parameters
# -------------------
telescope:
  # Focal length in millimeters
  focal_length: 3454
  # Aperture diameter in millimeters
  aperture: 508
  # Telescope type (refractor, reflector, etc.)
  type: "reflector"
  # Focal ratio (focal_length / aperture)   TODO: Replace with calculation
  focal_ratio: 6.8

# Camera Parameters
# ----------------
camera:
  # Sensor width in millimeters
  sensor_width: 36.0
  # Sensor height in millimeters
  sensor_height: 24.0
  # Pixel size in micrometers
  pixel_size: 3.76
  # Camera type (mono, color, etc.)
  type: "mono"
  # Bit depth
  bit_depth: 16

# Video Capture Settings
# ---------------------
video:
  # Camera device index
  camera_index: 0
  # Camera type: 'opencv' for regular video cameras, 'ascom' for astro cameras
  camera_type: "ascom"
  # ASCOM driver ID for astro cameras (e.g., "ASCOM.QHYCamera.Camera", "ASCOM.ZWOCamera.Camera")
  ascom_driver: ""
  # Frame width in pixels
  frame_width: 1920
  # Frame height in pixels
  frame_height: 1080
  # Frame rate
  fps: 30
  # Auto exposure (true/false)
  auto_exposure: false
  # Manual exposure time in seconds
  exposure_time: 10.0
  # Gain setting
  gain: 1.0

# Plate-Solving Settings
# ----------------------
plate_solve:
  # Enable automatic plate-solving
  auto_solve: true
  # Minimum interval between solves in seconds
  min_solve_interval: 30
  # Save frames for plate-solving
  save_plate_solve_frames: true
  # Plate-solving output directory
  plate_solve_dir: "plate_solve_frames"
  # Default solver to use (platesolve2, astrometry)
  default_solver: "platesolve2"
  # PlateSolve 2 specific settings
  platesolve2_path: "C:/Program Files (x86)/PlaneWave Instruments/PWI3/PlateSolve2/PlateSolve2.exe"
  working_directory: "C:/Users/BP34_Admin/AppData/Local/Temp"
  timeout: 60
  verbose: true
  auto_mode: true  # Enable automatic solving
  silent_mode: true  # Enable silent mode
  result_file_pattern: "*.txt"  # Pattern for result files
  number_of_regions: 999  # Number of regions to test
  search_radius: 15  # degrees
  min_stars: 20
  max_stars: 200
  # Astrometry.net specific settings
  astrometry_api_key: ""
  astrometry_api_url: "http://nova.astrometry.net/api/"

# Overlay Generation Settings
# ---------------------------
overlay:
  # Field of view in degrees
  field_of_view: 1.5
  # Maximum magnitude of objects to display
  magnitude_limit: 9.0
  # Include objects without magnitude (galaxies, etc.)
  include_no_magnitude: false
  # Object types to include (empty = all types)
  # Common types: *, G (galaxy), AG? (active galaxy), Le? (lens), etc.
  object_types: []
  # Image size in pixels (width, height)
  image_size: [1920, 1080]
  # Font size for object labels
  font_size: 14
  # Output file format
  output_format: "png"
  # Default output filename
  default_filename: "overlay.png"
  # Maximum length for object names (truncate if longer)
  max_name_length: 15

# Streaming Settings
# ------------------
streaming:
  # Update interval in seconds
  update_interval: 30
  # Maximum consecutive failures before stopping
  max_retries: 3
  # Delay between retry attempts in seconds
  retry_delay: 5
  # Enable timestamped filenames
  use_timestamps: true
  # Timestamp format for filenames
  timestamp_format: "%Y%m%d_%H%M%S"

# Display Settings
# ----------------
display:
  # Object marker color (RGB)
  object_color: [255, 0, 0]  # Red
  # Text color (RGB)
  text_color: [255, 255, 255]  # White
  # Object marker size in pixels
  marker_size: 5
  # Text offset from marker in pixels
  text_offset: [8, -8]

# Logging Settings
# ----------------
logging:
  # Enable detailed logging
  verbose: true
  # Log level: DEBUG, INFO, WARNING, ERROR
  level: "INFO"
  # Log to file
  log_to_file: false
  # Log file path
  log_file: "telescope_streaming.log"

# Platform Settings
# -----------------
platform:
  # Font paths for different operating systems
  fonts:
    windows:
      - "arial.ttf"
      - "C:/Windows/Fonts/arial.ttf"
    linux:
      - "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
      - "/usr/share/fonts/TTF/arial.ttf"
    macos:
      - "/System/Library/Fonts/Arial.ttf"
      - "/Library/Fonts/Arial.ttf"

# Advanced Settings
# -----------------
advanced:
  # Enable coordinate transformation debugging
  debug_coordinates: false
  # Enable SIMBAD query debugging
  debug_simbad: true
  # Save empty overlays when no objects found
  save_empty_overlays: true
  # Enable automatic error recovery
  auto_recovery: true 