# ASI2600MC Pro Configuration
# Configuration for ZWO ASI2600MC Pro camera with 80mm APO telescope

# =============================================================================
# CAMERA CONFIGURATION (Unified for all operations)
# =============================================================================
camera:
  # Camera type and basic settings
  camera_type: "alpaca"  # "ascom", "alpaca", or "opencv"

  # Sensor specifications (important for calibration)
  sensor_width: 23.5     # Sensor width in mm
  sensor_height: 15.7    # Sensor height in mm
  pixel_size: 3.76       # Pixel size in micrometers
  type: "color"          # Camera type (mono, color)
  bit_depth: 16          # Bit depth

  # Cooling settings for ASCOM cameras
  cooling:
    enable_cooling: true           # Enable camera cooling
    target_temperature: -5.0      # Target temperature in Celsius
    wait_for_cooling: false         # Wait for target temperature before capture
    cooling_timeout: 300           # Cooling timeout in seconds
    stabilization_tolerance: 1.0   # Temperature tolerance in Celsius
    warmup_rate: 2.0              # Warmup rate in °C per minute
    warmup_final_temp: 15.0       # Final temperature for warmup
    warmup_at_end: true           # Start warmup when stopping observation
    status_interval: 30           # Status update interval in seconds

  # ASCOM camera settings
  ascom:
    ascom_driver: "ASCOM.ASICamera2.Camera"  # ASCOM driver ID for astro cameras
    exposure_time: 10.0  # Manual exposure time in seconds
    gain: 100.0  # Gain setting
    offset: 50  # Offset setting (0-255 typically)
    readout_mode: 0  # Readout mode (camera-specific)
    binning: 1  # Binning factor (1x1, 2x2, etc.)
    # Optional: Separate filter wheel driver (e.g., for QHY cameras -- "ASCOM.QHYCFW.FilterWheel")
    filter_wheel_driver: null  # Filter wheel driver ID (if applicable)

  # Alpaca camera settings
  alpaca:
    host: "localhost"
    port: 11111
    device_id: 0
    exposure_time: 10.0  # Manual exposure time in seconds
    gain: 100.0  # Gain setting
    offset: 50  # Offset setting (0-255 typically)
    readout_mode: 0  # Readout mode (camera-specific)
    binning: [1, 1]  # Binning factor [x, y] for Alpaca

  # OpenCV camera settings
  opencv:
    camera_index: 0  # Camera device index
    exposure_time: 0.1  # Exposure time in seconds
    gain: 1.0  # Gain setting
    resolution: [1920, 1080]  # Resolution [width, height]
    frame_rate: 30  # Frame rate

# =============================================================================
# FRAME PROCESSING CONFIGURATION (Image capture and processing)
# =============================================================================
frame_processing:
  enabled: true

  # Frame saving settings
  use_timestamps: false  # Enable timestamps in frame filenames
  timestamp_format: "%Y%m%d_%H%M%S"  # Timestamp format for filenames
  use_capture_count: false  # Enable capture count in frame filenames

  # Processing settings
  auto_debayer: true  # Auto-debayer color images
  debayer_method: "RGGB"  # Debayer pattern (RGGB, BGGR, GRBG, GBRG)

  # Normalization settings for display (OpenCV conversion)
  normalization:
    method: zscale    # zscale | hist
    contrast: 0.15    # zscale contrast parameter

  # Output settings
  output_dir: "captured_frames"  # Directory for captured frames
  cache_dir: "cache"  # Directory for temporary files
  file_format: "PNG"  # File format for saved frames (fits, jpg, png, tiff, etc.)

# =============================================================================
# TELESCOPE CONFIGURATION
# =============================================================================
telescope:
  # Focal length in millimeters
  focal_length: 400  # 80mm APO with 5x focal ratio
  # Aperture diameter in millimeters
  aperture: 80
  # Telescope type (refractor, reflector, etc.)
  type: "refractor"
  # Focal ratio (focal_length / aperture)
  focal_ratio: 5.0

# =============================================================================
# MOUNT CONFIGURATION
# =============================================================================
mount:
  # ASCOM driver program ID
  driver_id: "ASCOM.tenmicron_mount.Telescope"
  # Connection timeout in seconds
  connection_timeout: 10
  # Coordinate validation
  validate_coordinates: true
  # Slewing detection settings
  slewing_detection:
    enabled: true  # Enable slewing detection to prevent captures during movement
    check_before_capture: true  # Check slewing status before each capture
    wait_for_completion: false  # Wait for slewing to complete before capturing
    wait_timeout: 300  # Maximum wait time in seconds (5 minutes)
    check_interval: 1.0  # Interval between slewing checks in seconds

# =============================================================================
# PLATE SOLVING CONFIGURATION
# =============================================================================
plate_solve:
  # General plate-solving settings
  auto_solve: true
  min_solve_interval: 30
  save_plate_solve_frames: true
  plate_solve_dir: "plate_solve_frames"
  default_solver: "astrometry_local"

  # Settings for PlateSolve2
  platesolve2:
    executable_path: "C:/Program Files (x86)/PlaneWave Instruments/PWI3/PlateSolve2/PlateSolve2.exe"
    working_directory: "C:/Users/BP34_Admin/AppData/Local/Temp"
    timeout: 60
    verbose: true
    auto_mode: true
    number_of_regions: 150
    min_stars: 20
    max_stars: 200

  # Settings Astrometry.net local
  astrometry_local:
    solve_field_path: "solve-field"
    working_directory: "astrometry_output"
    timeout: 240
    search_radius_deg: 3.5
    downsample: 2
    scale_pad_arcsec: 0.3
    use_bash: true
    bash_path: "bash"        # oder voller Pfad zu bash.exe
    bash_args: ["-lc"]

  # Settings for Astrometry.net
  astrometry:
    api_key: ""
    api_url: "http://nova.astrometry.net/api/"

# =============================================================================
# OVERLAY CONFIGURATION
# =============================================================================
overlay:
  # Wait indefinitely for plate-solving results before generating overlay
  wait_for_plate_solve: true
  # Field of view in degrees (default if not provided by plate-solving)
  field_of_view: 1.5
  # Maximum magnitude of objects to display
  magnitude_limit: 9.0
  # Include objects without magnitude (e.g. galaxies)
  include_no_magnitude: false
  # Image size for overlay generation
  image_size: [6248, 4176]  # Full sensor resolution
  # Font size for text
  font_size: 35
  # Output format for overlays
  output_format: "png"
  # Default filename for overlays
  default_filename: "overlay.png"
  # Maximum length for object names
  max_name_length: 15
  # Use timestamps in overlay filenames
  use_timestamps: false
  # Timestamp format for overlay filenames
  timestamp_format: "%Y%m%d_%H%M%S"
  # Update settings
  update:
    update_interval: 30
    max_retries: 3
    retry_delay: 5
  # Display settings
  display:
    object_color: [255, 0, 0]
    text_color: [255, 255, 255]
    marker_size: 20
    text_offset: [35, -35]

  # Coordinates settings
  coordinates:
    force_flip_x: false
    force_flip_y: false
    rotation_offset_deg: 201.2
    use_wcs_projection: true

  # Information panel settings
  info_panel:
    enabled: true
    position: "top_right"  # "top_left", "top_right", "bottom_left", "bottom_right"
    width: 1300
    background_color: [0, 0, 0, 180]  # RGBA with transparency
    border_color: [255, 255, 255, 255]
    border_width: 2
    padding: 10
    line_spacing: 10
    font_size: 50
    text_color: [255, 255, 255, 255]
    title_color: [255, 255, 0, 255]  # Yellow for title
    show_timestamp: true
    show_coordinates: true
    show_telescope_info: true
    show_camera_info: true
    show_fov_info: true
    show_plate_solve_info: true

  # Title/Header settings
  title:
    enabled: true
    text: "OST Telescope Streaming - 80mm APO + ASI2600MC Pro"
    position: "top_center"  # "top_center", "top_left", "top_right"
    font_size: 65
    font_color: [255, 255, 0, 255]  # Yellow
    background_color: [0, 0, 0, 180]  # Semi-transparent black
    padding: 10
    border_color: [255, 255, 255, 255]
    border_width: 1

  # Secondary telescope FOV overlay settings
  secondary_fov:
    enabled: true  # Enable/disable secondary FOV display
    type: "camera"  # "camera" or "eyepiece"

    # Secondary telescope parameters
    telescope:
      focal_length: 3454  # Focal length in mm
      aperture: 508       # Aperture in mm
      type: "reflector"   # Telescope type

    # For camera-based FOV
    camera:
      sensor_width: 36.0   # Sensor width in mm
      sensor_height: 24.0  # Sensor height in mm
      pixel_size: 3.76     # Pixel size in micrometers
      type: "mono"         # Camera type (mono/color)

    # For eyepiece-based FOV
    eyepiece:
      focal_length: 36     # Eyepiece focal length in mm
      afov: 68             # Apparent Field of View in degrees

    # Display settings
    display:
      color: [0, 255, 255, 255]  # Cyan color (RGBA)
      line_width: 2
      style: "dashed"      # "solid", "dashed", "dotted"
      opacity: 180         # Transparency (0-255)
      show_label: true     # Show FOV label
      label_color: [0, 255, 255, 255]  # Label color
      label_font_size: 30
      label_offset: [5, 5]  # Label offset from FOV border

    # Position offset (if secondary telescope is not perfectly aligned)
    position_offset:
      ra_offset_arcmin: 0.0   # RA offset in arcminutes
      dec_offset_arcmin: 0.0  # Dec offset in arcminutes

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  verbose: true
  level: "INFO"
  show_emojis: false
  log_to_file: false
  log_file: "telescope_streaming.log"

# =============================================================================
# PLATFORM CONFIGURATION
# =============================================================================
platform:
  fonts:
    windows: ["arial.ttf", "C:/Windows/Fonts/arial.ttf"]
    linux: ["/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", "/usr/share/fonts/TTF/arial.ttf"]
    macos: ["/System/Library/Fonts/Arial.ttf", "/Library/Fonts/Arial.ttf"]

# =============================================================================
# ADVANCED CONFIGURATION
# =============================================================================
advanced:
  debug_coordinates: false
  debug_simbad: false
  save_empty_overlays: true
  auto_recovery: true
