# OST Telescope Streaming Configuration
# =====================================

# Telescope Mount Settings
# ------------------------
mount:
  # ASCOM driver program ID
  driver_id: "ASCOM.tenmicron_mount.Telescope"
  # Connection timeout in seconds
  connection_timeout: 10
  # Coordinate validation
  validate_coordinates: true

# Telescope Parameters
# -------------------
telescope:
  # Focal length in millimeters
  focal_length: 3454
  # Aperture diameter in millimeters
  aperture: 508
  # Telescope type (refractor, reflector, etc.)
  type: "reflector"
  # Focal ratio (focal_length / aperture)   TODO: Replace with calculation
  focal_ratio: 6.8

# Camera Parameters
# ----------------
camera:
  # Sensor width in millimeters
  sensor_width: 36.0
  # Sensor height in millimeters
  sensor_height: 24.0
  # Pixel size in micrometers
  pixel_size: 3.76
  # Camera type (mono, color, etc.)
  type: "mono"
  # Bit depth
  bit_depth: 16

# Video Capture Settings
# ---------------------
video:
  video_enabled: true
  camera_type: "ascom"  # or "ascom"

  # Settings only for OpenCV cameras
  opencv:
    camera_index: 0
    frame_width: 1920  # Frame width in pixels
    frame_height: 1080  # Frame height in pixels
    fps: 30  # Frames per second
    auto_exposure: true  # Enable auto exposure
    exposure_time: 0.1  # Manual exposure time in seconds
    gain: 1.0  # Gain setting

  # Settings only for ASCOM cameras
  ascom:
    ascom_driver: "ASCOM.QHYCCD.Camera"  # ASCOM driver ID for astro cameras
    exposure_time: 2.0  # Manual exposure time in seconds
    gain: 1.0  # Gain setting
    binning: 2  # Binning factor (1x1, 2x2, etc.)
    # Separate filter wheel driver for QHY cameras
    filter_wheel_driver: "ASCOM.QHYCFW.FilterWheel"  # QHY filter wheel driver

  # Frame saving settings
  use_timestamps: false  # Enable timestamps in frame filenames
  timestamp_format: "%Y%m%d_%H%M%S"  # Timestamp format for filenames
  use_capture_count: false  # Enable capture count in frame filenames
  file_format: "png"  # File format for saved frames (fits, jpg, png, tiff, etc.)

# Plate-Solving Settings
# ----------------------
plate_solve:
  # General plate-solving settings
  auto_solve: true
  min_solve_interval: 30
  save_plate_solve_frames: true
  plate_solve_dir: "plate_solve_frames"
  default_solver: "platesolve2"

  # Settings for PlateSolve2
  platesolve2:
    executable_path: "C:/Program Files (x86)/PlaneWave Instruments/PWI3/PlateSolve2/PlateSolve2.exe"
    working_directory: "C:/Users/BP34_Admin/AppData/Local/Temp"
    timeout: 60
    verbose: true
    auto_mode: true
    number_of_regions: 150
    min_stars: 20
    max_stars: 200

  # Settings for Astrometry.net
  astrometry:
    api_key: ""
    api_url: "http://nova.astrometry.net/api/"

# Overlay Generation Settings
# ---------------------------
overlay:
  # Wait indefinitely for plate-solving results before generating overlay
  wait_for_plate_solve: true
  # Field of view in degrees (default if not provided by plate-solving)
  field_of_view: 1.5
  # Maximum magnitude of objects to display
  magnitude_limit: 9.0
  # Include objects without magnitude (e.g. galaxies)
  include_no_magnitude: false
  # Object types to include (empty = all types)
  object_types: []
  # Image size in pixels (width, height)
  image_size: [1920, 1080]
  # Font size for object labels
  font_size: 14
  # Output file format (e.g. png, jpg)
  output_format: "png"
  # Default output filename
  default_filename: "overlay.png"
  # Maximum length for object names (truncate if longer)
  max_name_length: 15
  # Enable timestamped filenames for overlays
  use_timestamps: false
  # Timestamp format for filenames
  timestamp_format: "%Y%m%d_%H%M%S"

  # Update settings (controls overlay update logic)
  update:
    # Interval between overlay updates in seconds
    update_interval: 30
    # Maximum consecutive failures before stopping
    max_retries: 3
    # Delay between retry attempts in seconds
    retry_delay: 5

  # Display settings (controls overlay appearance)
  display:
    # Object marker color (RGB)
    object_color: [255, 0, 0]  # Red
    # Text color (RGB)
    text_color: [255, 255, 255]  # White
    # Object marker size in pixels
    marker_size: 5
    # Text offset from marker in pixels
    text_offset: [8, -8]

# Logging Settings
# ----------------
logging:
  # Enable detailed logging
  verbose: true
  # Log level: DEBUG, INFO, WARNING, ERROR
  level: "INFO"
  # Log to file
  log_to_file: false
  # Log file path
  log_file: "telescope_streaming.log"

# Platform Settings
# -----------------
platform:
  # Font paths for different operating systems
  fonts:
    windows:
      - "arial.ttf"
      - "C:/Windows/Fonts/arial.ttf"
    linux:
      - "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
      - "/usr/share/fonts/TTF/arial.ttf"
    macos:
      - "/System/Library/Fonts/Arial.ttf"
      - "/Library/Fonts/Arial.ttf"

# Advanced Settings
# -----------------
advanced:
  # Enable coordinate transformation debugging
  debug_coordinates: false
  # Enable SIMBAD query debugging
  debug_simbad: true
  # Save empty overlays when no objects found
  save_empty_overlays: true
  # Enable automatic error recovery
  auto_recovery: true 