[tool.ruff]
line-length = 100
select = ["E", "F", "I", "B"]
ignore = ["E203"]

[tool.ruff.isort]
known-first-party = ["code"]
force-sort-within-sections = true

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true
strict_optional = true
no_implicit_optional = true
show_error_codes = true
exclude = ["tests/"]

[tool.black]
line-length = 100
